### ISSUE TITLE
LIMS connection error

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#79]
Sometimes when running variant calling, the `clarity` module fails to connect to the dev instance of the LIMS, crashing the pipeline. It usually happens when the LIMS hasn't been accessed for a long time.

**Comment by mwhamgenomics** [comment]
Stacktrace:

``` python
Traceback (most recent call last):
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/requests-2.8.1-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/requests-2.8.1-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "/home/U008/mwham/python/master/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/home/U008/mwham/python/master/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/home/U008/mwham/python/master/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/U008/mwham/python/master/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/requests-2.8.1-py3.4.egg/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/requests-2.8.1-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/requests-2.8.1-py3.4.egg/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/requests-2.8.1-py3.4.egg/requests/packages/urllib3/packages/six.py", line 310, in reraise
    raise value
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/requests-2.8.1-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/requests-2.8.1-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 380, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/requests-2.8.1-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='egclaritydev.mvm.ed.ac.uk', port=8080): Read timed out. (read timeout=16)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/genologics-b_v0.2.3_871_g4e40b92_r0-py3.4.egg/genologics/lims.py", line 62, in get
    timeout=TIMEOUT)
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/requests-2.8.1-py3.4.egg/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/requests-2.8.1-py3.4.egg/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/requests-2.8.1-py3.4.egg/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/requests-2.8.1-py3.4.egg/requests/adapters.py", line 435, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='egclaritydev.mvm.ed.ac.uk', port=8080): Read timed out. (read timeout=16)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/U008/mwham/Analysis-Driver/analysis_driver/client.py", line 127, in _process_dataset
    exit_status = driver.pipeline(d)
  File "/home/U008/mwham/Analysis-Driver/analysis_driver/driver.py", line 24, in pipeline
    exit_status = variant_calling_pipeline(dataset)
  File "/home/U008/mwham/Analysis-Driver/analysis_driver/driver.py", line 162, in variant_calling_pipeline
    fastq_pair = _bcbio_prepare_sample(sample_dir, sample_id, fastq_files)
  File "/home/U008/mwham/Analysis-Driver/analysis_driver/driver.py", line 242, in _bcbio_prepare_sample
    user_sample_id = clarity.get_user_sample_name(sample_id)
  File "/home/U008/mwham/Analysis-Driver/analysis_driver/clarity/__init__.py", line 99, in get_user_sample_name
    sample = get_lims_sample(sample_name, lims)
  File "/home/U008/mwham/Analysis-Driver/analysis_driver/clarity/__init__.py", line 85, in get_lims_sample
    samples = get_lims_samples(sample_name, lims)
  File "/home/U008/mwham/Analysis-Driver/analysis_driver/clarity/__init__.py", line 73, in get_lims_samples
    samples = lims.get_samples(name=sample_name)
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/genologics-b_v0.2.3_871_g4e40b92_r0-py3.4.egg/genologics/lims.py", line 255, in get_samples
    return self._get_instances(Sample, params=params)
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/genologics-b_v0.2.3_871_g4e40b92_r0-py3.4.egg/genologics/lims.py", line 374, in _get_instances
    root = self.get(self.get_uri(klass._URI), params=params)
  File "/home/U008/mwham/python/28_10_analysis_driver/lib/python3.4/site-packages/genologics-b_v0.2.3_871_g4e40b92_r0-py3.4.egg/genologics/lims.py", line 64, in get
    raise type(e)("{0}, Error trying to reach {1}".format(e.message, uri))
AttributeError: 'ReadTimeout' object has no attribute 'message'
```

**Comment by tcezard** [comment]
I'm not sure what is happening here it might just be that the LIMS is slow to wake up 
We can increase the timeout on the genologics interface or at least make it configurable
https://github.com/EdinburghGenomics/genologics/blob/master/genologics/lims.py#L25

**Comment by tcezard** [comment]
Actually the error should not be a AttributeError but a ReadTimeout. This seems to be a bug introduced in the python2-->python3 conversion

**Comment by tcezard** [comment]
This seems to happen in production as well so we should try to reproduce it if we can.
One solution would be to allow for retries up to 3 times which might give the LIMS enough time to wake up

**Comment by tcezard** [comment]
the bug still exist but is not a problem anymore
